### PR TITLE
change default temp folder used by ui

### PR DESCRIPTION
**Pull request by jomrs**
as stated here: https://github.com/azuritecoin/OnnxDiffusersUI/discussions/107 
since gradio uses the lib tempfile to store generated files to be displayed by ui, the files are saved on OS "temp" folder. it is not a problem in linux as how the temp folder works, but on windows it stays until user cleans it. so this modification changes the default temp folder to "temp" in the same folder of onnxUI.py, then when stopping the ui using **CTRL+C** it tries to clear the folder.

obs: this changes tempdir instead of env variables such as "TEMP" or "TMP", because when i was trying changing them it didn't seems to take any effect.

### CODE REVIEW

**Comment by xzuyn** [comment]
it cleans but you need to press ctrl+c again to actually close.

**Comment by azuritecoin** [comment]
Leaving a comment here so I'll remember to test this later this week.

**Comment by azuritecoin** [comment]
I'll probably continue using ctrl-C to close the script

**Comment by xzuyn** [comment]
its been working great, only happened a couple times where i needed to press ctrl+c again since i last commented.

**Pull request merged**
