### PR TITLE
Update requirements to install Diffusers from github --main repo and include current Schedulers

### PR DESCRIPTION
**Pull request by averad**
Updated requirements.txt to use `git+https://github.com/huggingface/diffusers.git` when installing diffusers
Updated the UI script to include new schedulers
Updated standalone script to accept `--scheduler` argument

### CODE REVIEW

**Comment by averad** [comment]
UI Updated Schedulers (Screenshot):

example

**Comment by averad** [comment]
Updated standalone script (screenshot):

example

**Comment by azuritecoin** [comment]
I'll merge this pull request now.

**Comment by azuritecoin** [comment]
DDPM seems to be giving bad results

**Comment by averad** [comment]
@azuritecoin DDPM takes 150 to 300 steps to generate an image, it's normal. Wasn't sure if it should be labeled as such in the UI or just expect users to know.

[Original Paper](https://arxiv.org/abs/2010.02502)

**Comment by azuritecoin** [comment]
I'd say leave it as is for now and I'll make a comment in the README.md. Users have other schedulers they can try.

**Pull request merged**
