### PR TITLE
Inpainting tab

### PR DESCRIPTION
**Pull request by azuritecoin**
- Added new tab for inpainting
- Added inpainting and legacy_inpainting

### CODE REVIEW

**Comment by azuritecoin** [comment]
Pinging @averad

**Comment by azuritecoin** [comment]
One thing I noticed is that only PNDM, DDIM, and DPMS schedulers work with legacy inpaint

**Comment by averad** [comment]
> One thing I noticed is that only PNDM, DDIM, and DPMS schedulers work with legacy inpaint

Yeah, they hopefully will update that soon. I haven't tested to see if the other schedulers work and just haven't been added.

**Comment by averad** [comment]
@azuritecoin tested out the updates, looks good 👍 

Issues:
* Legacy Pipeline uses a lower # of steps than what is submitted (Hugging Face issue)

**Pull request merged**
